app/lets_quiz/lets_quiz/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from quiz import views as quiz_views
from django.conf.urls import handler404, handler500
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('quiz.urls')),
]


handler404 = quiz_views.error_404
handler500 = quiz_views.error_500


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/lets_quiz/quiz/urls.py
from django.conf.urls import url
from . import views

app_name = 'quiz'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^user-home$', views.user_home, name='user_home'),
    url(r'^play/$', views.play, name='play'),
    url(r'^leaderboard/$', views.leaderboard, name='leaderboard'),
    url(r'^submission-result/(?P<attempted_question_pk>\d+)/', views.submission_result, name='submission_result'),
    url(r'^login/', views.login_view, name='login'),
    url(r'^logout/', views.logout_view, name='logout'),
    url(r'^register/', views.register, name='register'),

]

app/lets_quiz/quiz/models.py
import random
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext as _
from model_utils.models import TimeStampedModel


class Question(TimeStampedModel):
    ALLOWED_NUMBER_OF_CORRECT_CHOICES = 1

    html = models.TextField(_('Question Text'))
    is_published = models.BooleanField(_('Has been published?'), default=False, null=False)
    maximum_marks = models.DecimalField(_('Maximum Marks'), default=4, decimal_places=2, max_digits=6)

    def __str__(self):
        return self.html


class Choice(TimeStampedModel):
    MAX_CHOICES_COUNT = 4

    question = models.ForeignKey(Question, related_name='choices', on_delete=models.CASCADE)
    is_correct = models.BooleanField(_('Is this answer correct?'), default=False, null=False)
    html = models.TextField(_('Choice Text'))

    def __str__(self):
        return self.html


class QuizProfile(TimeStampedModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    total_score = models.DecimalField(_('Total Score'), default=0, decimal_places=2, max_digits=10)

    def __str__(self):
        return f'<QuizProfile: user={self.user}>'

    def get_new_question(self):
        used_questions_pk = AttemptedQuestion.objects.filter(quiz_profile=self).values_list('question__pk', flat=True)
        remaining_questions = Question.objects.exclude(pk__in=used_questions_pk)
        if not remaining_questions.exists():
            return
        return random.choice(remaining_questions)

    def create_attempt(self, question):
        attempted_question = AttemptedQuestion(question=question, quiz_profile=self)
        attempted_question.save()

    def evaluate_attempt(self, attempted_question, selected_choice):
        if attempted_question.question_id != selected_choice.question_id:
            return

        attempted_question.selected_choice = selected_choice
        if selected_choice.is_correct is True:
            attempted_question.is_correct = True
            attempted_question.marks_obtained = attempted_question.question.maximum_marks

        attempted_question.save()
        self.update_score()

    def update_score(self):
        marks_sum = self.attempts.filter(is_correct=True).aggregate(
            models.Sum('marks_obtained'))['marks_obtained__sum']
        self.total_score = marks_sum or 0
        self.save()


class AttemptedQuestion(TimeStampedModel):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    quiz_profile = models.ForeignKey(QuizProfile, on_delete=models.CASCADE, related_name='attempts')
    selected_choice = models.ForeignKey(Choice, on_delete=models.CASCADE, null=True)
    is_correct = models.BooleanField(_('Was this attempt correct?'), default=False, null=False)
    marks_obtained = models.DecimalField(_('Marks Obtained'), default=0, decimal_places=2, max_digits=6)

    def get_absolute_url(self):
        return f'/submission-result/{self.pk}/'

app/lets_quiz/quiz/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, get_user_model
from django.utils.translation import gettext as _
from .models import Question, Choice


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['html', 'is_published']
        widgets = {
            'html': forms.Textarea(attrs={'rows': 3, 'cols': 80}),
        }


class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['html', 'is_correct']
        widgets = {
            'html': forms.Textarea(attrs={'rows': 2, 'cols': 80}),
        }


class ChoiceInlineFormset(forms.BaseInlineFormSet):
    def clean(self):
        super(ChoiceInlineFormset, self).clean()

        correct_choices_count = 0
        for form in self.forms:
            if not form.is_valid():
                return

            if form.cleaned_data and form.cleaned_data.get('is_correct') is True:
                correct_choices_count += 1

        try:
            assert correct_choices_count == Question.ALLOWED_NUMBER_OF_CORRECT_CHOICES
        except AssertionError:
            raise forms.ValidationError(_('Exactly one correct choice is allowed.'))


User = get_user_model()


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("This user does not exists")
            if not user.check_password(password):
                raise forms.ValidationError("Incorrect password")
            if not user.is_active:
                raise forms.ValidationError("This user is not active")
        return super(UserLoginForm, self).clean(*args, **kwargs)


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        ]

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

app/lets_quiz/quiz/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404
from .models import QuizProfile, Question, AttemptedQuestion
from .forms import UserLoginForm, RegistrationForm


def home(request):
    context = {}
    return render(request, 'quiz/home.html', context=context)


@login_required()
def user_home(request):
    context = {}
    return render(request, 'quiz/user_home.html', context=context)


def leaderboard(request):

    top_quiz_profiles = QuizProfile.objects.order_by('-total_score')[:500]
    total_count = top_quiz_profiles.count()
    context = {
        'top_quiz_profiles': top_quiz_profiles,
        'total_count': total_count,
    }
    return render(request, 'quiz/leaderboard.html', context=context)


@login_required()
def play(request):
    quiz_profile, created = QuizProfile.objects.get_or_create(user=request.user)

    if request.method == 'POST':
        question_pk = request.POST.get('question_pk')

        attempted_question = quiz_profile.attempts.select_related('question').get(question__pk=question_pk)

        choice_pk = request.POST.get('choice_pk')

        try:
            selected_choice = attempted_question.question.choices.get(pk=choice_pk)
        except ObjectDoesNotExist:
            raise Http404

        quiz_profile.evaluate_attempt(attempted_question, selected_choice)

        return redirect(attempted_question)

    else:
        question = quiz_profile.get_new_question()
        if question is not None:
            quiz_profile.create_attempt(question)

        context = {
            'question': question,
        }

        return render(request, 'quiz/play.html', context=context)


@login_required()
def submission_result(request, attempted_question_pk):
    attempted_question = get_object_or_404(AttemptedQuestion, pk=attempted_question_pk)
    context = {
        'attempted_question': attempted_question,
    }

    return render(request, 'quiz/submission_result.html', context=context)


def login_view(request):
    title = "Login"
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('/user-home')
    return render(request, 'quiz/login.html', {"form": form, "title": title})


def register(request):
    title = "Create account"
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login')
    else:
        form = RegistrationForm()

    context = {'form': form, 'title': title}
    return render(request, 'quiz/registration.html', context=context)


def logout_view(request):
    logout(request)
    return redirect('/')


def error_404(request):
    data = {}
    return render(request, 'quiz/error_404.html', data)


def error_500(request):
    data = {}
    return render(request, 'quiz/error_500.html', data)

app/lets_quiz/templates/quiz/error_404.html
{% extends 'base.html' %}
{% block title %} Let's Quiz | Page does not exists {% endblock title %}
{% block content %}
	<div class="container">
		<div class="alert alert-danger text-center" role="alert">
	          <h4 class="alert-heading">Error 404: Page not found</h4>
	          <p>The page you are looking does not exists. <a href="{% url 'quiz:home' %}" class="alert-link">Go back to homepage</a></p>
        </div>
    </div>

{% endblock content %}

app/lets_quiz/templates/quiz/error_500.html
{% extends 'base.html' %}
{% block title %} Let's Quiz | Internal Server Error {% endblock title %}
{% block content %}
	<div class="container">
		<div class="alert alert-danger text-center" role="alert">
	          <h4 class="alert-heading">Internal Server Error</h4>
	          <p>There is some error in internal server, we will be back soon.</p>
        </div>
    </div>

{% endblock content %}

app/lets_quiz/templates/quiz/home.html
{% extends 'base.html' %}
{% block title %} Let's Quiz | Home {% endblock title %}
{% block content %}

    <section id="section-jumbotron" class="jumbotron jumbotron-fluid d-flex justify-content-center align-items-center">
      <div class="container text-center">
        <h1 class="display-1 text-info">Let's Quiz</h1>

        <!-- FIX ME -->
        <p class="display-4 d-none d-sm-block">Test your skills and become a master.</p>

        {% if not request.user.is_active %}
        <p class="lead">Sign up if you haven't already and get access to millions of quizzes on the topic of your interest.</p>
        <p><strong> Start Your Journey Here:</strong></p>
        {% endif %}
      </div>  
    </section>

{% endblock content %}

app/lets_quiz/templates/quiz/leaderboard.html
{% extends 'base.html' %}
{% block title %} Let's Quiz | Leaderboard {% endblock title %}
{% block content %}
<div class="container">
    <h1 class="text-center my-4"><span class="badge badge-info"><i class="fa fa-trophy" aria-hidden="true"></i> TOP {{ total_count }} PLAYERS <i class="fa fa-trophy" aria-hidden="true"></i></span></h1>
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Position</th>
                <th>Username</th>
                <th>Score</th>
            </tr>
        </thead>
        <tbody>
            {% for quiz_profile in top_quiz_profiles %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ quiz_profile.user.username }}</td>
                <td>{{ quiz_profile.total_score }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

app/lets_quiz/templates/quiz/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Let's Quiz | {{ title }} {% endblock title %}
{% block content %}
{% if not request.user.is_active %}

    <div class="jumbotron jumbotron-fluid">
        <div class="container">
          <div class="row">
            <div class="col-12 col-sm-8 col-md-6 col-lg-4 offset-sm-2 offset-md-3 offset-lg-4">
              <h1 class="mb-3 text-center">Please log in</h1>
                <form method="POST" action="">
                    {% csrf_token %}
                    {{form|crispy}}
                    <input type="submit" class="btn btn-info btn-block" value="{{ title }}"> 
                </form>
              <div class="text-center">
                <p>or ...</p>
                <a href="{% url 'quiz:register' %}" class="btn btn-success mb-3">Create account</a>
              </div>
            </div>
          </div>
        </div>
      </div>
{% else %}

    <section id="section-jumbotron" class="jumbotron jumbotron-fluid d-flex justify-content-center align-items-center">
      <div class="container text-center">
        <h1 class="display-1 text-info">Let's Quiz</h1>
        <p class="display-4 d-none d-sm-block">Test your skills and become a master.</p>
        <p class="lead">We organize quizzes on various topics.</p>
        <a href="{% url 'quiz:play' %}" class="btn btn-lg btn-info mt-1">Let's play</a>
        <a href="{% url 'quiz:leaderboard' %}" class="btn btn-lg btn-info mt-1">Leaderboard</a>
      </div>  
    </section>

{% endif %}

{% endblock content %}

app/lets_quiz/templates/quiz/play.html
{% extends 'base.html' %}

{% block content %}
{% if question is None %}

<div class="container">
  <div class="jumbotron my-4">
    <h1> You have already answered all of our questions. </h1>
    <a href="{% url 'quiz:leaderboard' %}" class="btn btn-lg btn-info"><i class="fa fa-trophy" aria-hidden="true"></i> See the leaderboard here <i class="fa fa-trophy" aria-hidden="true"></i></a>
  </div>
</div>

{% else %}

<div class="container">
  <div class="jumbotron my-4">

    <h3 class="text-info">{{ question.html|safe }}</h3>
    <form class="form" action="" method="post">
        {% csrf_token %}
        <input type="hidden" name="question_pk" value="{{ question.pk }}">
        {% for choice in question.choices.all %}
          <div class="form-check mx-4">
            <input class="form-check-input" type="radio" name="choice_pk" id="choice-{{ forloop.counter }}" value="{{ choice.pk }}">
            <label class="form-check-label" for="choice-{{ forloop.counter }}">
              {{ choice.html|safe }}
            </label>
          </div>

        {% endfor %}
        <input class="btn btn-info btn-lg" type="submit" value="Submit">  
    </form>
  </div>
</div>
{% endif %}

{% endblock content %}

app/lets_quiz/templates/quiz/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Let's Quiz | {{ title }} {% endblock title %}
{% block content %}
{% if not request.user.is_active %}

     <div class="jumbotron jumbotron-fluid">
        <div class="container">
          <div class="row">
            <div class="col-12 col-sm-8 col-md-6 col-lg-4 offset-sm-2 offset-md-3 offset-lg-4">
              <h1 class="mb-3 text-center">Create a new account</h1>
              <form class="mb-3" method="POST" action="">
                {% csrf_token %}
		        {{form|crispy}}
		        <input type="submit" class="btn btn-info btn-block mb-3" value="{{ title }}"> 
              </form>
              <div class="text-center">
                <p>or ...</p>
                <a href="{% url 'quiz:login' %}" class="btn btn-success">Login</a>
              </div>
            </div>
          </div>
        </div>
      </div>

{% else %}

    <section id="section-jumbotron" class="jumbotron jumbotron-fluid d-flex justify-content-center align-items-center">
      <div class="container text-center">
        <h1 class="display-1 text-info">Let's Quiz</h1>
        <p class="display-4 d-none d-sm-block">Test your skills and become a master.</p>
        <p class="lead">We organize quizzes on various topics.</p>
        <a href="{% url 'quiz:play' %}" class="btn btn-lg btn-info mt-1">Let's play</a>
        <a href="{% url 'quiz:leaderboard' %}" class="btn btn-lg btn-info mt-1">Leaderboard</a>
      </div>  
    </section>

{% endif %}

{% endblock content %}

app/lets_quiz/templates/quiz/submission_result.html
{% extends 'base.html' %}
{% block title %} Let's Quiz | Submission Result {% endblock title %}
{% block content %}
<div class="container">
	<div class="jumbotron my-4">

	   	<h3 class="text-info">{{ attempted_question.question.html|safe }}</h3>

		<p>
		    <strong>Your answer: </strong>
		    {{ attempted_question.selected_choice.html|safe }}
		</p>

		{% if attempted_question.selected_choice.is_correct %}
		<h4 class="text-success">Yayy!! Your answer is correct. High Five! 🙌</h4>
		{% else %}
		<h4 class="text-danger">Your answer is incorrect 😟</h4>
		{% endif %}

		<a class="btn btn-info" href="{% url 'quiz:play' %}">Show next question</a>
	</div>
</div>

{% endblock content %}

app/lets_quiz/templates/quiz/user_home.html
{% extends 'base.html' %}
{% block title %} Let's Quiz | Welcome {% endblock title %}
{% block content %}
<div class="container my-4">
    <div class="jumbotron">

	      <h2 class="text-center text-info">Congratulations!! You have successfully logged in.</h2>
	      <h3 class="text-info text-center">Before you play the quiz, here are the rules</h3>

        <div class="row">

            <div class="card border-info mx-4 my-4">
                <div class="card-body text-info">
                    <h4 class="card-title">Rules :</h4>
                    <p class="card-text">
                        <ul style="list-style:decimal;">
                            <li>All questions are multiple choice question.</li>
                            <li><span class="text-danger">Only one choice is correct.</span></li>
                            <li>Every question carry equal marks i.e. <span class="text-danger">4 marks for each question.</span>
                            </li>
                            <li>Every question is displayed only once per user.</li>
                            <li>Try to answer as quickly as you can.</li>
                            <li>If you press refresh or go back to the previous page, there will be a new question for you and the question you were on will be counted as attempted.</li>
                            <li>Questions are displayed randomly for every user.</li>
                            <li>You will be told immediately whether your answer was correct or incorrect once you submit the answer.</li>
                        </ul>
                    </p>
                    <a href="{% url 'quiz:play' %}" class="btn btn-info">Let's play</a>
                </div>  
                <div class="card-footer">Rules last modified 08-March-2018</div>  
            </div>  
        </div>  

    </div>
</div>
{% endblock content %}